language: python
# should work in 2.5 as well, but the test code depends on unittest library from python3.3
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
#install: "..." ## no dependencies
# command to run tests
script: nosetests
