language: python
# should work in 2.5 as well, but the test code depends on unittest library from python3.3
# we're attempting to mock up open() - for some reason it fails on python3.3 and python3.4
python:
  - "3.5"
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
#install: "..." ## no dependencies
# command to run tests
script: nosetests
